#############################################################################
# Makefile for building: Othello
# Generated by qmake (2.01a) (Qt 4.7.0) on: Fri Nov 26 23:22:04 2010
# Project:  Othello.pro
# Template: app
# Command: /home/mariuska/qtsdk-2010.05/qt/bin/qmake -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile Othello.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2010.05/qt/mkspecs/linux-g++ -I. -I../../qtsdk-2010.05/qt/include/QtCore -I../../qtsdk-2010.05/qt/include/QtGui -I../../qtsdk-2010.05/qt/include/QtWebKit -I../../qtsdk-2010.05/qt/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/mariuska/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/mariuska/qtsdk-2010.05/qt/lib -lQtWebKit -lQtGui -L/home/mariuska/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/mariuska/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = boardwidget.cpp \
		historydialog.cpp \
		main.cpp \
		mainwindow.cpp \
		minimax.cpp \
		minioptionsdialog.cpp \
		optionsdialog.cpp \
		othello.cpp \
		player.cpp \
		scorewidget.cpp \
		helpdialog.cpp moc_boardwidget.cpp \
		moc_historydialog.cpp \
		moc_mainwindow.cpp \
		moc_minioptionsdialog.cpp \
		moc_optionsdialog.cpp \
		moc_scorewidget.cpp \
		moc_helpdialog.cpp \
		qrc_resource.cpp
OBJECTS       = boardwidget.o \
		historydialog.o \
		main.o \
		mainwindow.o \
		minimax.o \
		minioptionsdialog.o \
		optionsdialog.o \
		othello.o \
		player.o \
		scorewidget.o \
		helpdialog.o \
		moc_boardwidget.o \
		moc_historydialog.o \
		moc_mainwindow.o \
		moc_minioptionsdialog.o \
		moc_optionsdialog.o \
		moc_scorewidget.o \
		moc_helpdialog.o \
		qrc_resource.o
DIST          = ../../qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		Othello.pro
QMAKE_TARGET  = Othello
DESTDIR       = 
TARGET        = Othello

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Othello.pro  ../../qtsdk-2010.05/qt/mkspecs/linux-g++/qmake.conf ../../qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/home/mariuska/qtsdk-2010.05/qt/lib/libQtWebKit.prl \
		/home/mariuska/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/home/mariuska/qtsdk-2010.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile Othello.pro
../../qtsdk-2010.05/qt/mkspecs/common/g++.conf:
../../qtsdk-2010.05/qt/mkspecs/common/unix.conf:
../../qtsdk-2010.05/qt/mkspecs/common/linux.conf:
../../qtsdk-2010.05/qt/mkspecs/qconfig.pri:
../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2010.05/qt/mkspecs/features/debug.prf:
../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2010.05/qt/mkspecs/features/qt.prf:
../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2010.05/qt/mkspecs/features/moc.prf:
../../qtsdk-2010.05/qt/mkspecs/features/resources.prf:
../../qtsdk-2010.05/qt/mkspecs/features/uic.prf:
../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
../../qtsdk-2010.05/qt/mkspecs/features/lex.prf:
../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/home/mariuska/qtsdk-2010.05/qt/lib/libQtWebKit.prl:
/home/mariuska/qtsdk-2010.05/qt/lib/libQtGui.prl:
/home/mariuska/qtsdk-2010.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile Othello.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Othello1.0.0 || $(MKDIR) .tmp/Othello1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Othello1.0.0/ && $(COPY_FILE) --parents boardwidget.h historydialog.h mainwindow.h minimax.h minioptionsdialog.h optionsdialog.h othello.h player.h scorewidget.h helpdialog.h .tmp/Othello1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/Othello1.0.0/ && $(COPY_FILE) --parents boardwidget.cpp historydialog.cpp main.cpp mainwindow.cpp minimax.cpp minioptionsdialog.cpp optionsdialog.cpp othello.cpp player.cpp scorewidget.cpp helpdialog.cpp .tmp/Othello1.0.0/ && (cd `dirname .tmp/Othello1.0.0` && $(TAR) Othello1.0.0.tar Othello1.0.0 && $(COMPRESS) Othello1.0.0.tar) && $(MOVE) `dirname .tmp/Othello1.0.0`/Othello1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Othello1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_boardwidget.cpp moc_historydialog.cpp moc_mainwindow.cpp moc_minioptionsdialog.cpp moc_optionsdialog.cpp moc_scorewidget.cpp moc_helpdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_boardwidget.cpp moc_historydialog.cpp moc_mainwindow.cpp moc_minioptionsdialog.cpp moc_optionsdialog.cpp moc_scorewidget.cpp moc_helpdialog.cpp
moc_boardwidget.cpp: boardwidget.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) boardwidget.h -o moc_boardwidget.cpp

moc_historydialog.cpp: historydialog.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) historydialog.h -o moc_historydialog.cpp

moc_mainwindow.cpp: mainwindow.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_minioptionsdialog.cpp: minioptionsdialog.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) minioptionsdialog.h -o moc_minioptionsdialog.cpp

moc_optionsdialog.cpp: optionsdialog.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) optionsdialog.h -o moc_optionsdialog.cpp

moc_scorewidget.cpp: scorewidget.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) scorewidget.h -o moc_scorewidget.cpp

moc_helpdialog.cpp: helpdialog.h
	/home/mariuska/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) helpdialog.h -o moc_helpdialog.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		html/installdox \
		html/minioptionsdialog_8h_source.html \
		html/tab_r.png \
		html/classBoardWidget-members.html \
		html/othello_8h_source.html \
		html/tab_l.png \
		html/minimax_8h_source.html \
		html/functions.html \
		html/player_8h_source.html \
		html/doxygen.png \
		html/classMainWindow-members.html \
		html/classOptionsDialog-members.html \
		html/classPlayer.html \
		html/classScoreWidget-members.html \
		html/helpdialog_8h_source.html \
		html/mainwindow_8h_source.html \
		html/classScoreWidget.html \
		html/doxygen.css \
		html/historydialog_8h_source.html \
		html/boardwidget_8h_source.html \
		html/functions_func.html \
		html/classBoardWidget.html \
		html/classMiniOptionsDialog.html \
		html/tab_b.png \
		html/classHelpDialog-members.html \
		html/files.html \
		html/classOptionsDialog.html \
		html/index.html \
		html/classOthello-members.html \
		html/classHistoryDialog.html \
		html/classMainWindow.html \
		html/optionsdialog_8h_source.html \
		html/tabs.css \
		html/classHelpDialog.html \
		html/classOthello.html \
		html/classPlayer-members.html \
		html/classes.html \
		html/annotated.html \
		html/scorewidget_8h_source.html \
		html/classHistoryDialog-members.html \
		html/classMiniOptionsDialog-members.html \
		html/search/all_62.html \
		html/search/all_61.html \
		html/search/close.png \
		html/search/classes_6d.html \
		html/search/functions_61.html \
		html/search/classes_70.html \
		html/search/nomatches.html \
		html/search/all_67.html \
		html/search/functions_67.html \
		html/search/all_68.html \
		html/search/all_6f.html \
		html/search/functions_6d.html \
		html/search/search.png \
		html/search/classes_73.html \
		html/search/classes_68.html \
		html/search/functions_7e.html \
		html/search/search.css \
		html/search/all_7e.html \
		html/search/all_6d.html \
		html/search/all_70.html \
		html/search/all_75.html \
		html/search/functions_75.html \
		html/search/all_69.html \
		html/search/classes_62.html \
		html/search/functions_69.html \
		html/search/search.js \
		html/search/all_73.html \
		html/search/classes_6f.html \
		html/search/functions_73.html \
		images/debian.png \
		images/save-icon.png \
		images/osfp.png \
		images/open-icon.png \
		images/help-icon.png \
		images/history-icon.png \
		images/archlinux.png \
		images/windows.png \
		images/white.png \
		images/about-icon.png \
		images/icon.png \
		images/java.png \
		images/exit-icon.png \
		images/qt.png \
		images/options-icon.png \
		images/validgreen.png \
		images/green.png \
		images/c.png \
		images/aek.png \
		images/new-icon.png \
		images/pao.png \
		images/black.png \
		images/mac.png
	/home/mariuska/qtsdk-2010.05/qt/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

boardwidget.o: boardwidget.cpp boardwidget.h \
		othello.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boardwidget.o boardwidget.cpp

historydialog.o: historydialog.cpp historydialog.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historydialog.o historydialog.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		historydialog.h \
		optionsdialog.h \
		minioptionsdialog.h \
		boardwidget.h \
		player.h \
		scorewidget.h \
		helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

minimax.o: minimax.cpp minimax.h \
		othello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minimax.o minimax.cpp

minioptionsdialog.o: minioptionsdialog.cpp minioptionsdialog.h \
		mainwindow.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minioptionsdialog.o minioptionsdialog.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		mainwindow.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

othello.o: othello.cpp othello.h \
		player.h \
		minimax.h \
		boardwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o othello.o othello.cpp

player.o: player.cpp player.h \
		scorewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

scorewidget.o: scorewidget.cpp scorewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scorewidget.o scorewidget.cpp

helpdialog.o: helpdialog.cpp helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpdialog.o helpdialog.cpp

moc_boardwidget.o: moc_boardwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boardwidget.o moc_boardwidget.cpp

moc_historydialog.o: moc_historydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_historydialog.o moc_historydialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_minioptionsdialog.o: moc_minioptionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minioptionsdialog.o moc_minioptionsdialog.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_scorewidget.o: moc_scorewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scorewidget.o moc_scorewidget.cpp

moc_helpdialog.o: moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpdialog.o moc_helpdialog.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

